Repository jenkins-x/environment-oss-weasel-dev, pull requests merged in 2020-07, with the labels that each got.

#25 chore: add configuration for JX codegen
  repositories/templates/jenkins-x.yaml
Labels: approved, lgtm, size/S

#26 chore: add arcalos cn-cicd secret
  env/templates/arcalos-cn-cicd-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#28 chore: remove arcalos version stream update
  env/templates/arcalos-version-stream-update-cj.yaml
Labels: approved, lgtm, size/M

#30 chore: remove arcalos cleanup script
  env/templates/arcalos-cleanup-cj.yaml
Labels: approved, lgtm, size/M

#29 chore: remove arcalos secrets and config
  env/templates/arcalos-alpha-prod-secret.yaml
  env/templates/arcalos-beta-preview-secret.yaml
  env/templates/arcalos-cn-cicd-secret.yaml
  env/templates/arcalos-config-configmap.yaml
  env/templates/datadog-dogrc-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/M

#31 chore: remove source repositories and schedulers
  env/templates/arcalos-boot-config-scheduler.yaml
  env/templates/arcalos-versions-scheduler.yaml
  repositories/templates/arcalos-boot-config-group.yaml
  repositories/templates/arcalos-versions-group.yaml
  repositories/templates/cloudbees.yaml
  repositories/templates/whitesource-group.yaml
Labels: approved, lgtm, size/L

#32 chore: remove jx-tenant-service
  repositories/templates/cloudbees.yaml
Labels: approved, lgtm, size/S

#34 chore: Bump jx-app-ui to 0.1.218
  env/jx-app-ui/templates/app.yaml
  env/requirements.yaml
Labels: approved, size/XS

#39 chore: Adding new Tekton controller e2e test to Lighthouse
  env/templates/lh-scheduler.yaml
Labels: approved, size/M

#40 chore: Add github.com/jenkins-x/lighthouse-jx-controller
  env/templates/lh-jx-scheduler.yaml
  repositories/templates/jenkins-x.yaml
  repositories/templates/lh-jx-group.yaml
Labels: approved, size/L

#42 fix: Report URL needs to be in lh-jx
  env/lighthouse-jx/values.tmpl.yaml
Labels: approved, size/XS

#43 fix: disable the jenkins master that decided to show up
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/XS
