Repository jenkins-x/environment-oss-weasel-dev, pull requests merged in 2020-06, with the labels that each got.

#1 chore: Populate approvers and turn on autoupdate
  OWNERS
  jx-requirements.yml
Labels: approved, size/M

#2 chore: Adding various secrets from tekton-weasel
  env/templates/arcalos-alpha-prod-secret.yaml
  env/templates/aws-creds-secret.yaml
  env/templates/bdd-secret.yaml
  env/templates/cb-chartmuseum-secret.yaml
  env/templates/chartmuseum-gcs-secret.yaml
  env/templates/core-chartmuseum-secret.yaml
  env/templates/datadog-dogrc-secret.yaml
  env/templates/external-dns-secret.yaml
  env/templates/featureflag-secret.yaml
  env/templates/gh-secret.yaml
  env/templates/gh-test-secret.yaml
  env/templates/git-test-bbs-approver-secret.yaml
  env/templates/git-test-bbs-secret.yaml
  env/templates/git-test-ghe-approver-secret.yaml
  env/templates/git-test-ghe-secret.yaml
  env/templates/git-test-gitlab-approver-secret.yaml
  env/templates/git-test-gitlab-secret.yaml
  env/templates/lighthouse-test-secret.yaml
  env/templates/tekton-artifact-bucket-secret.yaml
  env/templates/terraform-secret.yaml
  env/templates/test-jenkins-user-secret.yaml
  env/templates/versions-test-secret.yaml
  env/templates/whitesource-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/L

#3 fix: autoUpdate should run at 5:00 on Tuesday, not 0:05.
  jx-requirements.yml
Labels: approved, size/XS

#4 chore: Move over most cronjobs and all schedulers
  env/templates/arcalos-boot-config-scheduler.yaml
  env/templates/arcalos-cleanup-cj.yaml
  env/templates/arcalos-version-stream-update-cj.yaml
  env/templates/arcalos-versions-scheduler.yaml
  env/templates/bdd-jx-scheduler.yaml
  env/templates/boot-config-scheduler.yaml
  env/templates/ci-scheduler.yaml
  env/templates/default-scheduler.yaml
  env/templates/dev-env-scheduler.yaml
  env/templates/e2e-gc-cj.yaml
  env/templates/env-scheduler.yaml
  env/templates/jx-issue-lifecycle-close-cj.yaml
  env/templates/jx-issue-lifecycle-rotten-cj.yaml
  env/templates/jx-issue-lifecycle-stale-cj.yaml
  env/templates/jx-scheduler.yaml
  env/templates/jx-versions-scheduler.yaml
  env/templates/lh-scheduler.yaml
  env/templates/rebase-and-lgtm-scheduler.yaml
  env/templates/sync-nginx-images-cj.yaml
  env/templates/sync-nginx-images-script-cm.yaml
  env/templates/whitesource-scheduler.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/XXL

#5 fix: I disabled three cronjobs I didn't mean to
  env/templates/arcalos-cleanup-cj.yaml
  env/templates/arcalos-version-stream-update-cj.yaml
  env/templates/e2e-gc-cj.yaml
Labels: approved, size/XS

#7 fix: Copying over version stream update cron
  env/templates/version-stream-update-cj.yaml
Labels: approved, size/M

#9 chore: Add jenkins-x/lighthouse repo, remove SDM apps
  env/jx-sdm-app/values.tmpl.yaml
  env/requirements.yaml
  env/tekton-sdm-app/values.tmpl.yaml
  repositories/templates/jenkins-x.yaml
  repositories/templates/lh-group.yaml
Labels: approved, size/M

#10 fix: Use the existing bucket for chartmuseum
  env/jenkins-x-platform/values.tmpl.yaml
Labels: approved, size/S

#11 fix: Add the copy-chart-index cronjob
  env/templates/copy-charts-index-cj.yaml
Labels: approved, size/M

#13 chore: add custom domain
  jx-requirements.yml
Labels: approved, size/S

#12 chore: Migrate SourceRepositories to oss-weasel
  repositories/templates/arcalos-boot-config-group.yaml
  repositories/templates/arcalos-versions-group.yaml
  repositories/templates/bdd-jx-group.yaml
  repositories/templates/boot-config-group.yaml
  repositories/templates/ci-group.yaml
  repositories/templates/cloudbees.yaml
  repositories/templates/jenkins-x-apps.yaml
  repositories/templates/jenkins-x-charts.yaml
  repositories/templates/jenkins-x-images.yaml
  repositories/templates/jenkins-x.yaml
  repositories/templates/jx-group.yaml
  repositories/templates/jx-versions-group.yaml
  repositories/templates/rebase-and-lgtm-group.yaml
  repositories/templates/whitesource-group.yaml
Labels: approved, lgtm, size/XXL

#15 chore: adjust jx-app-ui subdomain
  env/jx-app-ui/values.yaml
Labels: approved, size/XS

#16 chore: jxui oauth2-proxy sso experiment
  env/jx-app-ui-sso-test/README.MD
  env/jx-app-ui-sso-test/templates/app.yaml
  env/jx-app-ui-sso-test/templates/ingress.yaml
  env/jx-app-ui-sso-test/values.yaml
  env/oauth-proxy-jxui-frontend/value.tmpl.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/L

#17 chore: rename jx-app-ui-sso-test jxuisso
  env/jxuisso/README.MD
  env/jxuisso/templates/app.yaml
  env/jxuisso/templates/ingress.yaml
  env/jxuisso/values.yaml
Labels: approved, lgtm, size/XS

#18 chore: arcalos beta preview sa
  env/templates/arcalos-beta-preview-secret.yaml
  env/values.tmpl.yaml
Labels: approved, lgtm, size/S

#21 fix: Add missing arcalos-config configmap
  env/templates/arcalos-config-configmap.yaml
Labels: approved, size/XS

#22 fix: Add netrc secret
  env/templates/netrc-secret.yaml
  env/values.tmpl.yaml
Labels: approved, size/S

#20 fix: set workload identity annotation for jxui
  env/jx-app-ui/values.yaml
  env/requirements.yaml
Labels: approved, lgtm, size/S

#23 chore: Configure SSO for JXUI
  env/jx-app-ui/values.yaml
  env/jxuisso/README.MD
  env/jxuisso/templates/app.yaml
  env/jxuisso/values.yaml
  env/oauth-proxy-jxui-frontend/value.tmpl.yaml
  env/oauth2-proxy-jxui/values.yaml
  env/requirements.yaml
  env/templates/jxui-oauth2-proxy-ingress.yaml
Labels: approved, lgtm, size/L
