Repository jenkins-x/environment-oss-weasel-dev, pull requests merged in 2020-08, with the labels that each got.

#45 fix: update with information for flagger, ingress, owasp-zap apps
  repositories/templates/jenkins-x-apps.yaml
Labels: approved, lgtm, size/M

#46 chore: Switch Lighthouse to rebase as merge method
  env/templates/lh-scheduler.yaml
Labels: approved, lgtm, size/XS

#47 chore: Disable boot-vault-tls on version stream
  env/templates/jx-versions-scheduler.yaml
Labels: approved, size/XS
