Repository jenkins-x/environment-oss-weasel-dev, pull requests merged in 2020-10, with the labels that each got.

#50 chore: adding jenkins context for Lighthouse
  env/templates/lh-scheduler.yaml
Labels: approved, lgtm, size/S

#51 chore: Remove unneeded GitHub and GitLab contexts from Lighthouse
  env/templates/lh-scheduler.yaml
Labels: approved, lgtm, size/M

#52 chore: Add gitea context (optional for the moment) for Lighthouse
  env/templates/lh-scheduler.yaml
Labels: approved, size/M
